### ISSUE TITLE
Multiplication is not accurate with three digist after comma

### ISSUE THREAD

**Issue by nikolaygit** [selfcontained/slikcalc#1]
The failure example can be tested on the main website: http://slikcalc.selfcontained.us/

(0.975 \* 1000) = 980.00

instead of 975.

The code I use:
setupPVAGFormulaCalc : function() {
        this.PVAGFormulaCalc = slikcalc.create('formula', {
            formula: '( {a} \* {b} )= {c}',
            calcOnLoad: true,
            registerListeners: true,
            vars: {
                a: { id: 'pvbeitragsatz_arbeitgeber' },
                b: { id: 'bruttogehalt'},
                c: { id: 'pvbeitrag_arbeitgeber'}
            }
        });
    },

I need this precision to do important open source calculation work. How can I fix this? Thank You!

**Comment by selfcontained** [comment]
I just need to make the precision configurable, it's set to 2 by default.

**Comment by selfcontained** [comment]
I added the ability to change the precision at a global level (2.0.1).  Just make a call like this somewhere before you run calculations on the page:

``` javascript
slikcalc.precision = 3; // defaults to 2
```

It would be better to be able and specify the precision on a calculator by calculator basis, but will require a bit more refactoring, and wanted to get this out for you.  Hopefully this unblocks you.

**Comment by nikolaygit** [comment]
Thank You Brad! This works flawlessly and is perfect for my calculations :)
