### ISSUE TITLE
Calculators fail to initialize if loaded via AJAX

### ISSUE THREAD

**Issue by rlewandowski** [selfcontained/slikcalc#4]
I don't know if the issue exists for all calculators, but at least FormulaCalc caused problems. 

Some part of calc initialization (in this case formula parsing) is waiting for window load event to occur. But this event will never be fired if html using the calculator will be loaded by ajax.

**Comment by selfcontained** [comment]
Looks like it would have been a problem for any calc.  Added a check to see if document has loaded prior to the slikcalc lib loading.  This is in 2.0.3, lemme know if you have any problems with it.

https://github.com/bmharris/slikcalc/commit/d807fc7c2a43617492292fa675bb0d49c5198b72
